Fantom/posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [

    path('',IndexView.as_view(),name="index"),
    path('detail/<int:pk>/<slug:slug>',PostDetail.as_view(),name="detail"),
    path('post-update/<int:pk>/<slug:slug>',UpdatePostView.as_view(),name="post_update"),
    path('post-delete/<int:pk>/<slug:slug>',DeletePostView.as_view(),name="post_delete"),
    path('category/<int:pk>/<slug:slug>',CategoryDetail.as_view(),name="category_detail"),
    path('tags/<slug:slug>',TagDetail.as_view(),name="tag_detail"),
    path('post-create',CreatePostView.as_view(),name="create_post"),
    path('search/',SearchView.as_view(),name='search'),
]

Fantom/users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as authViews

app_name ="users"
urlpatterns = [

    path('',UserListView.as_view(),name="user_list"),
    path('register/',RegisterView.as_view(),name="register"),
    path('contact/',ContactView.as_view(),name="contact"),
    path('contact-message/',ContactMessage.as_view(),name="contact-message"),
    path('login/',UserLoginView.as_view(),name="login"),
    path('logout/',UserLogoutView.as_view(),name="logout"),
    path('myprofile/',UserProfileView.as_view(),name="myprofile"),
    path('<int:pk>/',UserPostView.as_view(),name="user_posts"),
    path('update-profile/<slug:slug>/',UserProfileUpdateView.as_view(),name="update_profile"),
    path('password-change/',authViews.PasswordChangeView.as_view(),name="password_change"),
    path('password-change-done/',authViews.PasswordChangeDoneView.as_view(),name="password_change_done"),

]

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Accounts.urls')),
]

hofvidz/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # Hall
    path('halloffame/create', views.CreateHall.as_view(), name='create_hall'),
    path('halloffame/<int:pk>', views.DetailHall.as_view(), name='detail_hall'),
    path('halloffame/<int:pk>/update', views.UpdateHall.as_view(), name='update_hall'),
    path('halloffame/<int:pk>/delete', views.DeleteHall.as_view(), name='delete_hall'),
    # Video
    path('halloffame/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

social_media_site/post/forms.py
from django import forms
from .models import PostIt


class PostItForm(forms.ModelForm):

    class Meta:
        model = PostIt
        fields = ['post_title', 'post_body']

Fantom/posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormMixin

from .models import Post,Category,Tag
# Create your views here.
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import PostCreationForm, PostUpdateForm,CreateCommentForm


class IndexView(ListView):
    template_name = "posts/index.html"
    model = Post
    context_object_name = 'posts'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['slider_posts'] = Post.objects.all().filter(slider_post=True)
        return context

class PostDetail(DetailView,FormMixin):
    template_name = 'posts/detail.html'
    model = Post
    context_object_name = 'single'
    form_class = CreateCommentForm

    def get(self, request, *args, **kwargs):
        self.hit = Post.objects.filter(id=self.kwargs['pk']).update(hit=F('hit')+1)
        return super(PostDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['previous'] = Post.objects.filter(id__lt=self.kwargs['pk']).order_by('-pk').first()
        context['next'] = Post.objects.filter(id__gt=self.kwargs['pk']).order_by('pk').first()
        context['form'] = self.get_form()
        return context

    def form_valid(self, form):
        if form.is_valid():
            form.instance.post = self.object
            form.save()
            return super(PostDetail, self).form_valid(form)
        else:
            return super(PostDetail, self).form_invalid(form)

    def post(self,*args,**kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_valid(form)

    def get_success_url(self):
        return reverse('detail',kwargs={"pk":self.object.pk,"slug":self.object.slug})





class CategoryDetail(ListView):
    model = Post
    template_name = 'categories/category_detail.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        self.category = get_object_or_404(Category,pk=self.kwargs['pk'])
        return Post.objects.filter(category=self.category).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super(CategoryDetail, self).get_context_data(**kwargs)
        self.category = get_object_or_404(Category,pk=self.kwargs['pk'])
        context['category'] = self.category
        return context

class TagDetail(ListView):
    model = Post
    template_name = 'tags/tag_detail.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        self.tag = get_object_or_404(Tag,slug=self.kwargs['slug'])
        return Post.objects.filter(tag=self.tag).order_by('id')

    def get_context_data(self,**kwargs):
        context = super(TagDetail, self).get_context_data(**kwargs)
        self.tag = get_object_or_404(Tag,slug=self.kwargs['slug'])
        context['tag'] = self.tag
        return context


@method_decorator(login_required(login_url='users/login'),name="dispatch")
class CreatePostView(CreateView):
    template_name = 'posts/create-post.html'
    form_class = PostCreationForm
    model = Post


    def get_success_url(self):
        return reverse('detail',kwargs={"pk":self.object.pk,"slug":self.object.slug})

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()

        tags = self.request.POST.get("tag").split(",")

        for tag in tags:
            current_tag = Tag.objects.filter(slug=slugify(tag))
            if current_tag.count()<1:
                create_tag = Tag.objects.create(title=tag)
                form.instance.tag.add(create_tag)
            else:
                existed_tag = Tag.objects.get(slug=slugify(tag))
                form.instance.tag.add(existed_tag)
        return super(CreatePostView, self).form_valid(form)



@method_decorator(login_required(login_url='users/login'),name="dispatch")
class UpdatePostView(UpdateView):
    model = Post
    template_name = 'posts/post-update.html'
    form_class = PostUpdateForm

    def get_success_url(self):
        return reverse('detail',kwargs={"pk":self.object.pk,"slug":self.object.slug})


    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.tag.clear()

        tags = self.request.POST.get("tag").split(",")

        for tag in tags:
            current_tag = Tag.objects.filter(slug=slugify(tag))
            if current_tag.count() < 1:
                create_tag = Tag.objects.create(title=tag)
                form.instance.tag.add(create_tag)
            else:
                existed_tag = Tag.objects.get(slug=slugify(tag))
                form.instance.tag.add(existed_tag)
        return super(UpdatePostView, self).form_valid(form)
    
    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        
        if self.object.user != request.user:
            return HttpResponseRedirect('/')
        return super(UpdatePostView, self).get(request,*args,**kwargs)



class DeletePostView(DeleteView):
    model = Post
    success_url = '/'
    template_name = 'posts/delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        else:
            return HttpResponseRedirect(self.success_url)

    def get(self,request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect('/')
        return super(DeletePostView, self).get(request, *args, **kwargs)

class SearchView(ListView):
    model = Post
    template_name = 'posts/search.html'
    paginate_by = 5
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get("q")

        if query:
            return Post.objects.filter(Q(title__icontains=query)|
                                       Q(content__icontains=query)|
                                       Q(tag__title__icontains=query)

                                       ).order_by('id').distinct()

        return Post.objects.all().order_by('id')





Fantom/users/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView,ListView, TemplateView

from posts.models import Post
from .forms import RegisterForm,UserProfileForm
from .models import UserProfile
from django.urls import reverse

class RegisterView(CreateView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = '/'

class ContactView(SuccessMessageMixin, TemplateView):
    template_name = 'contact.html'

class ContactMessage(SuccessMessageMixin, TemplateView):
    template_name = 'contact.html'
    success_message = "Your P!!!"


class UserLoginView(LoginView):
    template_name = 'users/login.html'

class UserLogoutView(LogoutView):
    template_name = 'users/login.html'



@method_decorator(login_required(login_url='/users/login'),name="dispatch")
class UserProfileUpdateView(SuccessMessageMixin,UpdateView):
    model = UserProfile
    template_name = 'users/profile-update.html'
    form_class = UserProfileForm
    success_message = "Your Profile Has Been Updated!!!"


    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        return super(UserProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('users:update_profile',kwargs={'slug':self.object.slug})
    
    
    def get(self,request,*args,**kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect('/')
        
        return super(UserProfileUpdateView, self).get(request,*args,**kwargs)



@method_decorator(login_required(login_url='/users/login'),name="dispatch")
class UserProfileView(ListView):
    template_name = 'users/my-profile.html'
    model = Post
    context_object_name = 'userposts'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['userprofile'] = UserProfile.objects.get(user=self.request.user)
        return context

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user).order_by('-id')

class UserPostView(ListView):
    template_name = 'users/user-post.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 5


    def get_queryset(self):
        return Post.objects.filter(user=self.kwargs['pk'])

class UserListView(ListView):
    template_name = 'users/user-list.html'
    model = UserProfile
    context_object_name = 'profiles'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        return context

social_media_site/post/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import PostIt
from .forms import PostItForm
from users.forms import UserUpdateInfoForm, UserImageExtensionForm
from django.contrib import messages
from django.core.paginator import Paginator


@login_required()
def home_page(request):
    if request.method == 'POST':
        form = PostItForm(request.POST)
        form.instance.posted_by = request.user

        if form.is_valid():
            form.save()
            return redirect('post-home')
    else:
        form = PostItForm()

    number_of_posts = PostIt.objects.filter(posted_by=request.user.id)

    post_it_list = PostIt.objects.order_by('-posted_date')
    paginator = Paginator(post_it_list, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'post_its': page_obj,
        'number_of_personal_posts': len(number_of_posts),
        'form': form
    }

    return render(request, 'post/home.html', context)


@login_required()
def single_post_it(request, post_it_id, update=None):
    data = PostIt.objects.get(id=post_it_id)

    update_screen = True if update == 'update' else False

    if request.method == 'POST':
        form = PostItForm(request.POST)
        if form.is_valid():
            data.post_title = form.instance.post_title
            data.post_body = form.instance.post_body
            data.save()
            return redirect('post-home')
    else:
        form_data = {'post_title': data.post_title, 'post_body': data.post_body}
        form = PostItForm(initial=form_data)

    context = {
        'post_it': PostIt.objects.get(id=post_it_id),
        'update': update_screen,
        'form': form
    }

    return render(request, 'post/single-postit.html', context)


@login_required()
def delete_post_it(request, post_it_id):
    PostIt.objects.filter(id=post_it_id).delete()
    return redirect('post-home')


@login_required()
def account_page(request):
    if request.method == 'POST':
        user_update_info_form = UserUpdateInfoForm(request.POST, instance=request.user)

        if hasattr(request.user, 'userimageextension'):
            user_image_extension_form = UserImageExtensionForm(request.POST, request.FILES,
                                                               instance=request.user.userimageextension)
        else:
            user_image_extension_form = UserImageExtensionForm(request.POST, request.FILES)

            user_image_extension_form.instance.user = request.user

        if user_update_info_form.is_valid() and user_image_extension_form.is_valid():
            user_update_info_form.save()
            user_image_extension_form.save()
            messages.success(request, 'Account Updated')
            return redirect('post-account')
    else:
        user_update_info_form = UserUpdateInfoForm(instance=request.user)
        if hasattr(request.user, 'userimageextension'):
            user_image_extension_form = UserImageExtensionForm(instance=request.user.userimageextension)
        else:
            user_image_extension_form = UserImageExtensionForm()

    context = {
        'user_update_info_form': user_update_info_form,
        'user_image_extension_form': user_image_extension_form
    }

    return render(request, 'post/account.html', context)


def about_page(request):
    return render(request, 'post/about.html')

Fantom/templates/posts/create-post.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Login</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>

						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->

        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">

                        <h2 style="text-align:center;color:blue">Create Post</h2>
                        <div class="blog_left_sidebar">
                            <form method="post" enctype="multipart/form-data">

                                {% csrf_token %}
                                {% if form.errors %}
                                <div id="errors">
                                    <div class="inner">
                                        <p style="color:red">Please correct the errors below</p>
                                        <ul>
                                            {% for field in form %}
                                            {% if field.errors %}
                                            <li>{{ form.label }} : {{ field.errors|striptags }}</li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                {% endif %}

                                {% for field in form %}
                                <div class="mt-10">
                                    {{ field }}
									</div>
                                {% endfor %}

                                <div class="mt-10">
										<input type="text" name="tag" placeholder="Tag" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Tag'" required="" class="single-input">
									</div>

                                <input type="submit" class="genric-btn success circle" style="float:right;margin-top:30px" value="Add Post">
                            </form>

                        </div>


                    </div>
                    {% include 'right_side.html' %}

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->

       {% endblock %}

Fantom/templates/posts/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Update Post</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>

						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->

        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">

                        <h2 style="text-align:center;color:blue">Are You Sure To Delete This Post?</h2>
                        <div class="blog_left_sidebar">
                            <form method="post">
                                {% csrf_token %}
                                <a href="{% url 'detail' object.pk object.slug %}" class="genric-btn info circle">No</a>
                                <button type="submit" class="genric-btn danger circle">Yes</button>
                            </form>


                        </div>


                    </div>
                    {% include 'right_side.html' %}

                </div>
            </div>
        </section>
        <!--================Blog Area =================-->

       {% endblock %}

Fantom/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Blog Post Details</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">Post Details</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->

        <!--================Blog Area =================-->
        <section class="blog_area p_120 single-post-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
       					<div class="main_blog_details">
       						<img class="img-fluid" src="{{ single.image.url }}" alt="">
       						<a href="#"><h4>{{ single.title }}</h4></a>
       						<div class="user_details">
       							<div class="float-left">
                                    {% for tag in single.tag.all %}
       								<a href="{% url 'tag_detail' tag.slug %}">{{ tag.title }}</a>
                                    {% endfor %}

       							</div>
       							<div class="float-right">
       								<div class="media">
       									<div class="media-body">
                                            <h5><a href="{% url 'users:user_posts' single.user.pk %}">{{ single.user.username }}</a></h5>
       										<p>{{ single.publishing_date }}</p>
       									</div>
       									<div class="d-flex">
       										<img src="{% static "img/blog/user-img.jpg" %}" alt="">

       									</div>
       								</div>
       							</div>
       						</div>

							<p> {{ single.content }}</p>
                            {% if single.user == request.user %}
                            <a href="{% url 'post_update' single.pk single.slug %}" class="genric-btn info circle">Update</a>
                            <a href="{% url 'post_delete' single.pk single.slug %}" class="genric-btn danger circle">Delete</a>
      						{% endif %}
                            <div class="news_d_footer">
      							<a href="#"><i class="lnr lnr lnr-heart"></i>Lily and 4 people like this</a>
      							<a class="justify-content-center ml-auto" href="#"><i class="lnr lnr lnr-bubble"></i>{{ single.comments.count }}</a>
      							<div class="news_socail ml-auto">
									<a href="#"><i class="fa fa-facebook"></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-youtube-play"></i></a>
									<a href="#"><i class="fa fa-pinterest"></i></a>
									<a href="#"><i class="fa fa-rss"></i></a>
								</div>
      						</div>
       					</div>
       					<div class="navigation-area">
                            <div class="row">
                                {% if previous %}
                                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                                    <div class="thumb">
                                        <a href="{% url 'detail' previous.pk previous.slug %}"><img class="img-fluid" src="{{ previous.image.url }}" alt="" style="width:60px;height:60px"></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="{% url 'detail' previous.pk previous.slug %}"><span class="lnr text-white lnr-arrow-left"></span></a>
                                    </div>
                                    <div class="detials">
                                        <p>Prev Post</p>
                                        <a href="{% url 'detail' previous.pk previous.slug %}"><h4>{{ previous.title }}</h4></a>
                                    </div>
                                </div>

                                {% else %}
                                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                                    <div class="thumb">
                                        <a href="#"><img class="img-fluid" src="{% static "img/blog/prev.jpg" %}" alt=""></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                                    </div>
                                    <div class="detials">
                                        <p>No Prev Post</p>
                                        <a href="#"><h4>No Prev Post</h4></a>
                                    </div>
                                </div>

                                {% endif %}
                                {% if next %}
                                <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                                    <div class="detials">
                                        <p>Next Post</p>
                                        <a href="{% url 'detail' next.pk next.slug %}"><h4>{{ next.title }}</h4></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="{% url 'detail' next.pk next.slug %}"><span class="lnr text-white lnr-arrow-right"></span></a>
                                    </div>
                                    <div class="thumb">
                                        <a href="{% url 'detail' next.pk next.slug %}"><img class="img-fluid" src="{{ next.image.url }}" alt="" style="width:60px;height:60px"></a>
                                    </div>
                                </div>
                                {% else %}
                                <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                                    <div class="detials">
                                        <p>No Next Post</p>
                                        <a href="#"><h4>No Next Post</h4></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                                    </div>
                                    <div class="thumb">
                                        <a href="#"><img class="img-fluid" src="{% static "img/blog/next.jpg" %}" alt=""></a>
                                    </div>
                                </div>

                                {% endif %}
                            </div>
                        </div>
                        <div class="comments-area">
                            <h4>{{ single.comment_count }} Comments</h4>
                            {% for comment in single.comments.all %}
                            <div class="comment-list">
                                <div class="single-comment justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb">
                                            <img src="{% static "img/blog/c1.jpg" %}" alt="">
                                        </div>
                                        <div class="desc">
                                            <h5><a href="#">{{ comment.name }}</a></h5>
                                            <p class="date">{{ comment.publishing_date }} </p>
                                            <p class="comment">
                                                {{ comment.content }}
                                            </p>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            {% endfor %}

                        </div>
                        <div class="comment-form">
                            <h4>Leave a Reply</h4>
                            {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <div id="form_errors">
                                    {% for key,value in form.errors.items %}
                                    <span class="fieldWrapper">
                                        {{ key }} : {{ value }}


                                    </span>
                                    {% endfor %}
                                </div>

                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>

                            </div>
                            {% endif %}
                            {% crispy form %}
                        </div>
        			</div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->

       {% endblock %}