Fantom/Fantom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('users/',include('users.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

carzone/carzone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('cars/', include('cars.urls')),
    path('accounts/', include('accounts.urls')),
    path('socialaccounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('Accounts.urls')),
]

elibrary/ReadBook/urls.py
from django.urls import path, include

from ReadBook import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "ReadBook"

urlpatterns = [

path('', views.loadBook, name="premiumbook"),
path('addbook/', views.addBook, name="addbook"),
path('description/<int:bid>/', views.bookDescription, name='description'),
path('delete/<int:bid>/', views.deleteBook, name='deletebook'),
]

# so we can upload files
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hofvidz/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # Hall
    path('halloffame/create', views.CreateHall.as_view(), name='create_hall'),
    path('halloffame/<int:pk>', views.DetailHall.as_view(), name='detail_hall'),
    path('halloffame/<int:pk>/update', views.UpdateHall.as_view(), name='update_hall'),
    path('halloffame/<int:pk>/delete', views.DeleteHall.as_view(), name='delete_hall'),
    # Video
    path('halloffame/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

elibrary/Accounts/models.py
from django.db import models

# Create your models here.

elibrary/ReadBook/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class UserInfo(models.Model):
	users = models.OneToOneField(User, on_delete=models.CASCADE)

	#these are extended models features
	user_type = models.CharField(max_length=6)

	def __str__(self):
		return self.users.username



class Book(models.Model):
	book_name = models.CharField(max_length=50)
	# "on_delete=models.CASCADE" - if User is deleted delete uploaded_by  
	uploaded_by = models.ForeignKey(UserInfo, on_delete=models.CASCADE) 
	book_price = models.IntegerField(default=0)
	book_type = models.CharField(max_length=10)
	book_cover = models.ImageField(upload_to='book_images/')
	book_description = models.TextField()
	book_category = models.CharField(max_length=30)
	book_file = models.FileField(upload_to='book/')
	upload_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.book_name)










elibrary/Accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User, auth
from django.contrib import messages 
from django.http import HttpResponse
from ReadBook.models import UserInfo

# Create your views here.
def register_user(request):
	if not request.user.is_authenticated:
		if request.method=="POST":
			first_name = request.POST['first_name']
			last_name = request.POST['last_name']
			username = request.POST['username']
			email = request.POST['email']
			user_type = request.POST['user_type']
			password1 = request.POST['password1']
			password2 = request.POST['password2']

			if password1 == password2:
				if User.objects.filter(username=username).exists():
					messages.info(request, 'username is taken, choose another!')
					return redirect('Accounts:register_user')

				elif User.objects.filter(email=email).exists():
					messages.info(request, 'Email is taken, choose another!')
					return redirect('Accounts:register_user')

				else:
					user = User.objects.create_user(username=username, password=password1,
						email=email, first_name=first_name, last_name=last_name)
					user.save()
					UserInfo.objects.create(id=user.id, 
						user_type=user_type, users_id = user.id)


					return redirect('Accounts:login_user')

			else:
				messages.info(request, 'Password didn\'t match')
				return redirect('Accounts:register_user')

		return render(request, 'Accounts/register.html')



def login_user(request):
	if not request.user.is_authenticated:
		if request.method == 'POST':
			username = request.POST['username']
			password = request.POST['password']

			user = auth.authenticate(username=username, password=password) # checks db for user
			if user is not None:
				auth.login(request, user)
				return redirect('/')

			else:
				messages.info(request, 'invalid credentials!')
				return redirect('Accounts:login_user')

		else:
			return render(request, 'Accounts/login.html')

	else:
		return HttpResponse('you are not permitted to view this page!')

def logout_user(request):
	auth.logout(request)
	return redirect("Accounts:login_user")




elibrary/ReadBook/views.py
from django.shortcuts import render, redirect
from .models import Book

from .decorators import author_only
from django.contrib.auth.decorators import login_required
# Create your views here.

def loadBook(request):
	books = Book.objects.all()
	return render(request, "ReadBook/Book.html", context={"books": books})
	
@login_required(login_url='/login/')
@author_only
def addBook(request):
	name = ''
	price = ''
	btype = ''
	cover = ''
	pdf = ''
	description = ''
	category = ''
	userid = ''


	if request.method == "POST":

		try:
			name = request.POST['name'].strip()
			btype = request.POST['type'].strip()
			description = request.POST['description']
			category = request.POST['category']
			cover = request.FILES.get('image', None)
			pdf = request.FILES.get('files')
			userid = request.user.id


			if btype != 'Free':
				price = int(request.POST['price'])
			else:
				price = 0

			Book.objects.create(book_name=name, book_price=price, book_type=btype,
				book_cover = cover, book_description = description, 
				book_category = category, book_file = pdf, uploaded_by_id=userid)

			return redirect('ReadBook:premiumbook')

		except Exception as e:
			print("Error: "+ str(e))



	return render(request, "ReadBook/AddBook.html", context={

		"bookname": name,
		"bookprice" : price,
		"description": description,
		"category": category

		})


def bookDescription(request, bid):

	book = None
	owner = False
	loggedin = True if request.user.is_authenticated else False

	if Book.objects.filter(id=bid).exists():
		try:
			book = Book.objects.get(id=bid)
			if loggedin:
				owner = True if Book.objects.get(pk= bid).uploaded_by_id == request.user.id else False

		except Exception as e:
			print(str(e))
	else:
		return redirect("ReadBook:premiumbook")

	return render(request, "ReadBook/BookDescription.html", context={

		'book' : book,
		'loggedin': loggedin,
		'owner': owner

		})

# he never gave a button for this method in the app so if you want to use it you have
# to call it manually through the url
@login_required(login_url='/login/')
@author_only
def deleteBook(request, bid):
	book = None
	if Book.objects.filter(id=bid).exists():
		book = Book.objects.get(id=bid)
		book.delete()
	return redirect('ReadBook:premiumbook')

elibrary/templates/ReadBook/AddBook.html


{% extends 'Base/Header.html' %} {% block content %} {% load static %}

       
       <form method="POST" enctype = "multipart/form-data" style="padding-top: 20px;" id="addbookfor">

        {% csrf_token %}
        <div class="input-field col s12 m6">

            <label for="bookname"> Book Title </label>
            <input type="text" name="name" id="bookname" class="validate" 
            required value="{{bookname}}">

        </div>


         <div class="input-field col s12 m6">

            <label for="category"> Book Category </label>
            <input type="text" name="category" id="category" class="validate" 
            required value="{{category}}">
            <!-- value="{{category}} is the value that gets sent in the form w/ the post req -->

        </div>


         <div class="col s12 m6">

            <label for="booktype" class="fs15"> Book Type: </label>
            <select name="type" id="booktype" style="display: block; " required>
              <option value="" disabled selected>Choose your option</option>
              <option value="Premium">Premium</option>
              <option value="Free">Free</option>


        </div>

        <div class="input-field col s12 m6">

            <label for="bookprice"> Book Price </label>
            <input type="Number" name="price" id="bookprice" class="validate" 
            required value="{{bookprice}}">

        </div>


        <div class="col s12 m6">

            <label for="bookcover"> Book Cover: </label>
            <div class="file-field input-field">

              <div class="btn">

                    <span>Upload</span>

                    <input type="file" name="image" accept="image/jpeg" 
                    id="bookcover">
              </div>
              <div class="file-path-wrapper">

                <input type="file-path validate" type="text" 
                placeholder="Upload book cover" id="bookcoverpath">

              </div>
            </div>

        </div>



<!-- book pdf -->
<div class="col s12 m6">

            <label for="bookfile"> Book File: </label>
            <div class="file-field input-field">

              <div class="btn">

                    <span>Upload</span>

                    <input type="file" name="file" accept="application/pdf" 
                    id="bookfile" required>
              </div>
              <div class="file-path-wrapper">

                <input type="file-path validate" type="text" 
                placeholder="Upload book pdf" id="bookfilepath">

              </div>
            </div>

        </div>

        <div class="col s12">
          <label for="bookdescription" class="fs15">Abstract of a book</label>
          <textarea
            name="description"
            id="bookdescription"
            style="height: 8rem; resize: none; border: solid 0.5px 
            #9e9e9e; margin-top: 5px" placeholder="Description" required>{{description}}
          </textarea>


        </div>

        <div>
          <div class="input-field col s12 m6">
          <button type="button" class="btn waves-effect waves-light" style="width: 100%;"
            id="cancel"
            >Cancel</button>
          </div>
        </div>



        <div>
          <div class="input-field col s12 m6">
          <button type="submit" 
          class="btn waves-effect waves-light" style="width: 100%;">Add Book</button>
          </div>
        </div>



       </form>




      </div>
    </div>
  </div>
</div>
<script>
  // for disabling price input filed
  

  //auto add text
  $(document).ready(function() {
    //on load
    if ($("#bookname").val()) {
      $("#add_title").text($("#bookname").val());
    }
    if ($("#category").val()) {
      $("#add_cat_type").text($("#category").val());
    }
    if ($("#bookdescription").val()) {
      $("#add_description").text($("#bookdescription").val());
    }
    //on change
    $("#bookname").change(function() {
      $("#add_title").text($(this).val());
    });
    $("#category").change(function() {
      $("#add_cat_type").text($(this).val());
    });
    $("#booktype").change(function() {
      $("#add_book_type").text(" | " + $("#booktype option:selected").val());
    });
    $("#bookdescription").change(function() {
      $("#add_description").text($(this).val());
    });
  });

  $(document).ready(function() {
    $("#cancel").click(function() {
      $("#addbookform").trigger("reset");
      $("#add_title").text("");
      $("#add_cat_type").text("");
      $("#add_description").text("");
    });
  });

  //to pre load images addded in the field
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader(); // reads a file from the input

      // a listener for load events that fires after the data is read by
      // reader.readAsDataURL
      reader.onload = function(e) {
        $("#uploadedpic").attr("src", e.target.result);
      };

      // reads the files data as a url
      reader.readAsDataURL(input.files[0]);
    }
  }

  // calls readURL
  $("#bookcover").change(function() {
    readURL(this);
  });

</script>
{% endblock %}

elibrary/templates/ReadBook/Book.html
{% extends 'Base/Header.html' %}
{% load static %}
{% block content %}

<div class="row">

{% if not books %}

	<h3 align="center" style="color: #9e9e9e">No Books to display</h3>

{% else %}

{% for book in books %} <!-- passed from the view -->

	<div class="col s6 m5 14">
		<div class="card">
			<div class="card-image">
				<a href="{% url 'ReadBook:description' book.id %}" style="color: white;">
				<img src="{{book.book_cover.url}}" style="height:290px; border: 1px solid #9e9e9e; padding: 5px"/>
					
				</a>
			</div>
			<div class="card-content" style="overflow:hidden; border-top: 1px solid
			rgba(113, 112, 112, 0.3); padding: 0px" >

			<div style="background: #26a69a; padding: 2px 13px;">
			<a href="" style="color: white;">
					<span class="card-title"> {{book.book_name|title}}</span>

			</a>
			</div>


			</div>

			<div style="margin-left: auto;">
				<a href="" class="btn-waves-effect">

					{{book.book_price|yesno:'$,Free'}} {% firstof book.book_price %}


				</a>

			</div>



	</div>


{% endfor %} {% endif %}


</div>

{% endblock %}

elibrary/templates/ReadBook/BookDescription.html
{% extends 'Base/Header.html' %} {% block content %}

    {% if not book.book_price %}
      <!-- free -->
      <a href="" class="btn waves-effect" style="width:100%" target="_blank"><i class="material-icons" style="vertical-align: inherit;"> chrome_reader_mode</i> Free </a>

      <!-- buy -->
      <div style="margin: 10px;">
        <form action="" method="POST">
          {% csrf_token %}
          <button class="btn waves-effect" type="submit" style="width:100%">
            ${{book.book_price}}
          </button>
        </form>
      </div>
      {% elif loggedin %}
      <!-- bought -->
      <div style="margin: 10px;">
        <a href="" class="btn waves-effect" style="width:100%" target="_blank"
          ><i class="material-icons" style="vertical-align: inherit;"> file_download</i> DOWNLOAD</a
        >
      </div>
      {% endif %}
    </div>
    <!-- image section ends -->

    <!-- description section -->
    <div class="col s12 m6 l7">
      <div class="" style="height:0px; min-height: 367px; margin-bottom: 13px; padding: 10px; border-bottom: 1px solid #8a8a8a82; overflow: hidden;">
        <h6 style="margin-top: 5px; font-weight: 501; display: inline-block;">
          Description:
        </h6>
        <i class="material-icons b_description_down">keyboard_arrow_down</i>
        <p style="text-align: justify; margin:5px 0px;">
          &emsp; {{book.book_description}}
        </p>
      </div>
    </div>
    <!-- description section ends -->

          </form>


{% endblock %}